import React from 'react'
import Link from 'gatsby-link'



const TosPage = () => (
    <div>
        <div className="container">
            <div className="col-md-12">
                <div className="tos">
                    <h3>LET'S DIVORCE PRIVACY POLICY</h3>
                    <p><strong>Last Modified: June 1, 2018</strong></p>
                    <p>Your privacy is important to us and we have prepared this Privacy Policy to explain to you how we collect, use and share your personal information. This Privacy Policy governs all mobile applications and websites owned or operated by LetsDivorce, LLC (“<strong>LetsDivorce</strong>” “<strong>we</strong>” or “<strong>us</strong>”), including the website located at <Link to="/">www.LetsDivorce.us</Link> (the “<strong>Site</strong>”) and any other websites, applications, interactive features, widgets and resources offered by LetsDivorce through Internet websites, mobile devices or other platforms (all of which are collectively referred to as the “<strong>Service</strong>” or “<strong>Service</strong>”). By using the Service, you consent to the collection and use of your personal information as outlined in this Privacy Policy. Please read this Privacy Policy carefully, and if you have any questions, feel free to contact us. When you use the Service, you also consent to our Terms of Service.</p> 
                    
                    <h4>1. Questions and Opt Out.</h4>
                    <p>If you would like to ask questions or provide comments regarding this Privacy Policy you may do so by sending us an e-mail at <strong><u>privacy@LetsDivorce.us</u></strong>. We will not disclose Personal Information to third parties for their direct marketing purposes without your consent. If, after providing consent, you want to opt out of having your Personal Information disclosed to third parties for their direct marketing purposes, please let us know by sending us an e-mail at <strong><u>privacy@LetsDivorce.us</u></strong>. Please be sure to include your full name, your LetsDivorce username, the e-mail address you used to sign up with LetsDivorce and your mailing address and specifically state that you do not want your personal information shared with third parties for their direct marketing purposes.</p> 

                    <h4>2. Updating Your Personal Information and Controlling Your Profile.</h4>
                    <p>The Service provides tools for you to correct, update, or edit your personal information and control your profile. You can edit your profile and other information at any time through the Service.</p> 

                    <h4>3. Information You Submit.</h4>
                    <p>When you register to become a member of the Service, we collect certain information about you which may include such information as your name, social security number, e-mail address, home address, phone number, gender, and date of birth as well as information about your children, outstanding legal proceedings, and descriptions of assets. When you make purchases in the Service, we may also collect your credit card and other payment-related information as well. We may also collect other personal information, including, without limitation, any personal information that you provide to us through the Services or in connection with any contests, sweepstakes and/or other promotions (collectively, “<strong>Personal Information</strong>”). When you post comments or content through the Service, your username and other Personal Information may be included in the message.</p> 
                    
                    <h4>4. Information We Automatically Collect.</h4>
                    <p>We automatically collect certain non-personal information to help us understand how our users use the Service (which we will refer to in this Privacy Policy, collectively, as “<strong>Usage Data</strong>”). We may automatically collect and use the data contained in log files. The information in log files may include your IP address, your ISP, the Web browser you used to visit the Service, the time you visited the Service, which web pages you visited on the Service, and other anonymous usage data.</p> 
                    <p>We may collect information about the device you use to access our Service, including the hardware model, operating system and version, MAC address, unique device identifier (“UDID”), phone number, International Mobile Equipment Identity (“IMEI”) and mobile network information. We may also collect your device location with your consent so that you can use location-based features.</p> 
                    <p>In addition, we may use a technology called “cookies” and similar technologies. A cookie is a small file that identifies you as a unique user. We may use cookies to improve the quality of our Service and make the Service easier to use. We do this by storing information (for example, settings preferences) about a particular user session in cookies in order to provide you with a seamless experience during a particular session. Certain of our “Service Providers” (as defined below) may use cookies or similar technologies in connection with the services they perform on our behalf. If you choose to do so, you can configure your browser to delete existing cookies or disable cookies altogether. However, certain features of the Service may not work if you delete or disable cookies.</p> 
                    <p>The Service does not respond to web browser “do not track” signals or other mechanisms that provide consumers the ability to exercise choice regarding the collection of Personal Information about an individual consumer’s online activities over time. Visit www.donottrack.us to find out more about “do not track.”</p> 
                    <p>We may work with third-party advertising companies that may use information about your use of the Service in order to provide advertisements about goods and services that may be of interest to you on the Service and on third party websites. From the Service, these companies may place or recognize a unique cookie on your computer or use other technologies such as web beacons or pixel tags. Our Privacy Policy does not cover any use of information that a third party ad serving company may collect from you.</p>    
                    
                    <h4>5. How We Use Information.</h4>
                    <p>We may use your Personal Information to notify you of new services, to send service notifications, to customize the advertising and content you see, to improve our services, to conduct research and to solicit your feedback and input about the Service, including by telephone call, email, or text message. For contests, sweepstakes, and other promotions conducted on or through the Service, we use the Personal Information that you provide to communicate with you regarding such contest, sweepstakes or other promotion and in accordance with the applicable rules.</p> 
                    
                    <h4>6. How We Share Your Information.</h4>
                    <p>Other than as set forth in this Privacy Policy, except for aggregate information that we may share with third parties in a manner that does not link such information to any individual, we will not share your Personal Information with third parties, unless you have given us permission to do so. Please note that certain personal information becomes public record when documents are filed with the federal or state government, or with a court. This Privacy Policy does not cover such information or similar filings or actions.</p> 
                    <p>We may sometimes use other businesses (“<strong>Service Providers</strong>”) to perform certain services for us, e.g., to provide certain services on our behalf, such as payment processing, hosting and maintenance, data storage and management services, production and fulfillment, and marketing and promotions. We provide our Service Providers with the information reasonably necessary for them to perform the services on our behalf. Each Service Provider must agree to implement and maintain reasonable security procedures and practices appropriate to the nature of the information involved in order to protect your information from unauthorized access, destruction, use, modification or disclosure.</p> 
                    <p>We may disclose aggregate Usage Data in order to (a) describe the use of the Service to our existing or potential business partners, advertisers, investors or other third parties; (b) comply with laws, regulations, court orders or subpoenas or in response to a government request; or (c) protect or exercise our legal rights or defend against legal claims. However, please be assured that this aggregate data will not involve the disclosure of Personal Information nor personally identify you or any other users of the Service.</p> 
                    
                    <h4>7. Other Authorized Disclosures.</h4>
                    <p>Notwithstanding anything in this Privacy Policy to the contrary, you understand and agree that LetsDivorce may access, preserve and disclose any information we have collected about you or that you have submitted: (a) in response to subpoenas, court orders or legal process, or to establish, protect or exercise our legal rights or defend against legal claims; (b) to protect the rights and property of LetsDivorce, its affiliates, or the public; (c) if we believe it is necessary in order to investigate, prevent or take action regarding illegal activities, fraud, copyright violations, trademark violations or other violations of the personal or intellectual property rights of others or situations involving potential threats to the safety of any person; (d) to our corporate affiliates, joint ventures or other companies under common control with LetsDivorce (in which case we will require such entities to honor this Privacy Policy); and (e) if LetsDivorce is acquired by or merged with another entity or in connection with a sale of our assets. In addition, LetsDivorce may forward any copyright infringement Notification, Counter Notification (as each of those terms is defined in the Terms of Service) or trademark infringement notice that you submit pursuant to LetsDivorce’s Terms of Service, and any related communications, to third parties.</p>

                    <h4>8. Public Areas.</h4> 
                    <p>Your use of areas of the Service that are intended for interaction with other users may reveal your username and may allow you to publish certain personal information about you. By choosing to use these areas, you understand and agree that anyone with access to those areas may access and forward any information about you that is contained in or that you post to those areas. As with any social networking service, you should use care when disclosing your personal information to strangers.</p> 

                    <h4>9. Links to Other Sites.</h4>
                    <p>The Service may contain links to websites operated and maintained by third parties over which we have no control. Privacy policies on such linked websites may be different from our Privacy Policy. You access such linked websites at your own risk. We encourage you to review the privacy policy of any such linked website you visit to understand that website’s collection, storage, and use of your information.</p> 

                    <h4>10. Security.</h4>
                    <p>The security of your Personal Information is important to us. We use standard security procedures and practices appropriate to the nature of the information in an effort to protect information from unauthorized access, destruction, use, modification or disclosure. We also require our Service Providers to implement and maintain reasonable security procedures and practices appropriate to the nature of the information we share with them. No data transmission over the Internet or any wireless network can be guaranteed to be 100% secure. As a result, while we strive to protect Personal Information, we cannot and do not guarantee or warrant the security of any information you transmit to or from the Service, and you do so at your own risk.</p> 

                    <h4>11. Children's Privacy Statement.</h4>
                    <p>We do not knowingly collect personally identifiable information from children under the age of thirteen (13). If we become aware that we have inadvertently received personally identifiable information from a user under the age of thirteen (13), we will delete such information from our records. Because we do not knowingly collect any personally identifiable information from children under the age of thirteen (13), we also do not knowingly distribute such information to third parties.</p> 
                    
                    <h4>12. Data Processing in the United States.</h4>
                    <p>Please be aware that your Personal Information and communications may be transferred to and maintained on servers or databases located outside your state, province, or country. If you are located outside of the United States, please be advised that we may process and store all information in the United States. The laws in the United States may not be as protective of your privacy as those in your location. By using our Service, you agree that the collection, use, transfer and disclosure of your Personal Information and communications will be governed by the applicable laws in the United States.</p>
                    
                    <h4>13. Changes.</h4>
                    <p>LetsDivorce may, in its sole and absolute discretion, change this Privacy Policy from time to time. All changes to the Privacy Policy will be effective when posted, and we will provide notification of such changes to you via the Service or contact information you may have provided to LetsDivorce upon registration. In order to continue using the Service following any changes to the Privacy Policy of which we notify you, you must agree to be bound by such changes. If you object to any such changes, your sole recourse shall be to cease using the Service.</p> 
                    <p>Effective date: June 1, 2018.</p> 

                </div>
            </div>
        </div>
    </div>
)

export default TosPage
