import React from 'react'
import Link from 'gatsby-link'



const TosPage = () => (
    <div>
        <div className="container">
            <div className="col-md-12">
                <div className="tos">
                <h3>LETS DIVORCE TERMS OF SERVICE</h3>
                
                    <p>The Let’s Divorce Terms of Service(the “<strong>Terms</strong>”) govern your use of the websites and mobile applications owned or operated by LetsDivorce, LLC(“<strong>LetsDivorce</strong>” “<strong>we</strong>” or “<strong>us</strong>”), including the website located at <Link to="/">www.letsdivorce.us</Link> (the “<strong>Site</strong>”) and any other websites and resources offered by LetsDivorce(collectively the “<strong>Service</strong>”).By using the Service, you affirm that you understand, and agree to these Terms.If you do not agree to these Terms, you may not use the Service.</p>
                
                <p><strong>LETSDIVORCE IS NOT A LAW FIRM.</strong> LetsDivorce provides a do -it - yourself divorce platform and additional features.Your use of the Service does not and will not create an attorney - client relationship between you and LetsDivorce.We do not provide legal advice through the Service.The Service may facilitate access or introductions to an attorney or other licensed professionals in various ways, including, for example, by providing you with their contact information.Our Services is not intended to and will not create an attorney - client relationship between you and LetsDivorce.</p>
                <p>Your personal situation and relationship to the law is unique, and no general information or technological tools like those that we provide will be appropriate for every circumstance.<strong>If you need legal advice for your specific situation, you should consult a licensed attorney in your area.</strong> Further, because the law often changes and is different in different jurisdictions, LetsDivorce does not guarantee that all of the information on the Site or Service is current, complete, or accurate.</p>

                <h4>1. Your Responsibilities.</h4>
                <p>In order to access some features of the Service, you must register to for the Platform to become a member of the Service.When you register for the Platform, LetsDivorce collects certain personal information about you.Because the protection of your personal information is important to us, we will only use information we obtain about you in accordance with LetsDivorce’s Privacy Policy.You agree that you will: (a) provide true, accurate, current and complete information when prompted(e.g., at registration); and(b) maintain and update such information so that it is true, accurate, current, and complete at all times.</p>
                <p>LetsDivorce may refuse to grant you access to the Platform, or revoke your access, for any reason in its sole discretion, including in the event that we determine that your registration impersonates someone else, is illegal, vulgar or otherwise offensive.You agree not to transfer or resell your use of or access to the Service to any third party.YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND FOR ANY AND ALL ACTIVITIES THAT ARE CONDUCTED THROUGH YOUR ACCOUNT.LETSDIVORCE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE ARISING FROM YOUR FAILURE TO ADEQUATELY SAFEGUARD YOUR PASSWORD OR FOR ANY ACTIONS OCCURRING UNDER YOUR PASSWORD.</p>
                <p>We value the integrity of the LetsDivorce community, and you agree not to use the Service to:</p>
                <ol>
                    <li>violate any local, state, national or international law or regulation;</li>
                    <li>transmit any material that is abusive, harassing, tortious, defamatory, vulgar, pornographic, obscene, libelous, invasive of another's privacy, hateful or racially, ethnically or otherwise objectionable;</li>
                    <li>transmit any material that you know to be false, inaccurate, or misleading;</li>
                    <li>stalk, harass, bully, or harm another individual;</li>
                    <li>transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation;</li>
                    <li>knowingly transmit any material that contains adware, malware, spyware, software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
                    <li>defeat or interfere with any security feature of the Service, or attempt to do so;</li>
                    <li>impersonate any person or entity, or otherwise misrepresent your affiliation with a person or entity;</li>
                    <li>interfere with or disrupt the Service or servers or networks connected to the Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Service; or</li>
                    <li>alter or modify any content or component of the Service, other than content you have posted using the Service.</li>
                </ol>

                <p>You further agree not to use or launch any automated system, including, without limitation, “robots, ” “spiders, ” “offline readers” or the like, that access the Service.LetsDivorce reserves the right to revoke these exceptions either generally or in specific cases.</p>

                <h4>2. Ownership of LetsDivorce Content; Restrictions on Use.</h4>
                <p>The content on the Service, including, without limitation, forms, photos, clips, videos, text, software, scripts, graphics, sounds, music, interactive features and the like(collectively, the “<strong>Content</strong>”) and the “LetsDivorce” word mark and the LetsDivorce design mark, as well as certain other of the names, logos and materials displayed on or through the Service that constitute trademarks, tradenames, service marks or logos(the “<strong>Marks</strong>”) are owned by or licensed to LetsDivorce and are subject to copyright, trademark, and other intellectual property rights under U.S.and international laws.You agree not to reproduce, copy, download, stream, capture, archive, upload, publish, broadcast, sell, resell, modify, translate, decompile, disassemble, reverse engineer or exploit for any purposes the Service or any portion of the Service, including, without limitation, the Content and the Marks, except as authorized by these Terms or as otherwise intended or authorized by LetsDivorce and its applicable licensors.</p>
                <p>The Service is provided for your personal, non - commercial use only, except that if you are an attorney or other professional(a “<strong>Professional</strong>”), you may use the Service and our Content as provided below.You must abide by all copyright notices, trademark notices, information and restrictions contained in or associated with any Content.You must not remove, alter, interfere with or circumvent any copyright, trademark or other proprietary notices marked on the Content or any digital rights management mechanism, device or other content protection or access control measure associated with the Content.</p>
                <p>A Professional may use the Service by registering in the name of a client.A Professional must register a new account for each of its clients and may not use any client account on behalf of any other client.By registering a new account on behalf of a client, Professional represents and warrants that(a) it has all right, authority, and permission from the client to open such account on client’s behalf and to provide LetsDivorce with the information, including personal information, of the client necessary to use the Service and(b) the client has been provided a copy of and agrees to these Terms and the Privacy Policy.LetsDivorce may suspend or terminate a Professional’s access to the Service for any reason, including if it believes that a Professional has violated any provision of this paragraph.</p>
                    
                <h4>3. Feedback.</h4>
                <p>We appreciate your feedback as we strive to make divorce better.You agree that LetsDivorce and its affiliates are free to use any ideas, know - how, concepts, techniques, comments, criticisms, reports or other feedback(“<strong>Feedback</strong>”), about the Site or the Services, from you to us.You acknowledge and agree that you have no expectation of compensation or confidentiality of any nature, and that LetsDivorce has no duties to you(including any duty to compensate you), with respect to such Feedback.</p>

                <h4>4. Infringement Notice Procedures – Copyrights and Trademarks.</h4>
                <p>If you are the owner of any exclusive right under copyright laws, or are authorized to act on behalf of such an owner, and you believe your work has been copied in a way that constitutes copyright infringement, please send LetsDivorce‘s copyright agent a Notification of claimed infringement with all of the following information: (a) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works are covered by a single Notification, a representative list of such works; (b) identification of the claimed infringing material and information reasonably sufficient to permit LetsDivorce to locate the material on the Service; (c) information reasonably sufficient to permit LetsDivorce to contact you, such as an address, telephone number, and, if available, an e - mail address; (d) a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent or the law; (e) a statement by you, made under penalty of perjury, that the above information in your Notification is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf; and (f) your physical or electronic signature. Please provide us with a Notification that includes all of the above enumerated information and e-mail or mail it to the following LetsDivorce copyright agent:</p>

                <p>LetsDivorce, LLC</p>
                <p>E-mail: intellectualproperty@LetsDivorce.com</p>

                <h4>5. Termination.</h4>
                <p>LetsDivorce reserves the right, in its sole discretion, to terminate your access to all or part of the Service, for any reason, with or without notice. FURTHER, YOU AGREE THAT LETSDIVORCE SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR REMOVING YOUR (OR ANY OTHER PERSON’S) USER SUBMISSIONS OR FEEDBACK OR SUSPENDING OR TERMINATING YOUR (OR ANY OTHER PERSON’S) ACCESS TO THE SERVICE (OR ANY PORTION THEREOF).</p> 

                <h4>6. Modifications to Service.</h4>
                <p>LetsDivorce reserves the right to modify or discontinue the Service with or without notice to you. LetsDivorce shall not be liable to you or any third party should LetsDivorce exercise its right to modify or discontinue the Service.</p>

                <h4>7. Links.</h4>
                <p>The Sevice may contain links to third party websites, images, videos, gifs, or other Internet resources that are not owned or controlled by LetsDivorce (“<strong>Third-Party Materials</strong>”). LetsDivorce’s provision of a link to any other Third-Party Materials is for your convenience only and does not signify LetsDivorce’s endorsement of such other website or resource or its contents. LETSDIVORCE SHALL HAVE NO RESPONSIBILITY OR LIABILITY FOR ANY CONTENT, INFORMATION, SOFTWARE, MATERIALS OR PRACTICES OF ANY THIRD-PARTY INCLUDING ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SERVICE OR ANY LINKED WEBSITE OR FEATURED IN ANY ADVERTISING.</p>

                <h4>8. Disclaimer of Warranties.</h4>      
                <p>YOU EXPRESSLY AGREE THAT USE OF THE SERVICE IS AT YOUR SOLE RISK. THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE FULLEST EXTENT PERMITTED BY LAW, LETSDIVORCE AND ITS AFFILIATES EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, WITH RESPECT TO THE SERVICE (INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND NON-INFRINGEMENT).</p> 
                <p>LetsDivorce and its affiliates make no warranties or representatins that the Service will meet your requirements or that the reslts that may be obtained from use of the Service will be accurate or reliable. Further, LetsDivorce and its affiliates make no warranties or representations about the availaility of the Service, the accuracy or completeness of content available on or through the Service, or the content of any w e bsites linked o the Service. LetsDivorce assumes no liability or responsibility for any: (a) errors, mistakes or inaccuracies of content or confidentiality; (b) personal injury or property damage, of any nature whatsoever, resulting from access to or use of the Service or inability to access or use the Service; (c) unauthorized access to or use of our servers and/or any and all personal information and/or financial information stored therein (including any and all User Submissions); (d) interruption or cessation of transmission to or from the Service; (e) any bugs, viruses, Trojan horses or the like which may be transmitted to or through the Service by any third party; and/or (f) loss or damage of any kind incurred as a result of the use of any content posted, e-mailed, transmitted or otherwise made available on or through the Service.</p> 
                
                <h4>9. LIMITATION OF LIABILITY.</h4>        
                <p>TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT WILL LETSDIVORCE OR ITS OFFICERS, EMPLOYEES, DIRECTORS, SHAREHOLDERS, SUBSIDIARIES, AFFILIATES, AGENTS OR LICENSORS BE LIABLE UNDER ANY THEORY OF LIABILITY (WHETHER IN CONTRACT, TORT, STATUTORY OR OTHERWISE) FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF REVENUES, PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SUCH PARTIES WERE ADVISED OF, KNEW OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM YOUR (OR ANYONE USING YOUR ACCOUNT'S) USE OF THE SERVICE. TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT WILL LETSDIVORCE OR ITS OFFICERS, EMPLOYEES, DIRECTORS, SHAREHOLDERS, SUBSIDIARIES, AFFILIATES, AGENTS OR LICENSORS BE LIABLE TO YOU FOR DAMAGES EXCEEDING THE GREATER OF (A) $750.00 AND (B) THE AMOUNTS PAID BY YOU TO LETSDIVORCE DURING THE SIX-MONTH PERIOD IMMEDIATELY PRECEDING THE INCIDENT GIVING RISE TO SUCH LIABILITY.</p> 

                <h4>10. Exclusions and Limitations.</h4>
                <p>Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the above limitations and disclaimers may not apply to you. To the extent LetsDivorce may not, as a matter of applicable law, disclaim any implied warranty or limit its liabilities, the scope and duration of such warranty and the extent of LetsDivorce’s liability shall be the minimum permitted under such applicable law.</p> 

                <h4>11. Indemnification.</h4> 
                <p>You agree to indmnify, defend, and hold harmless LetsDivorce, its subsidiaries, affiliates, officers, directors, employees, consultants, and agents (“<strong>Indemnified Parties</strong>”) from and against any and all claims, liabilities, damages, losses, costs, expenses, fees (including reasonable attorneys' fees and costs) that they may incur as a result of or arising from: (a) any information you submit, post or transmit on or through the Service or otherwise provide to us; (b) your use of the Service; (c) your violation of these Terms or any Additional Terms; or (d) the violation of any rights of any other person or entity, including, without limitation, any copyright, patent, trademark, trade secret or other proprietary rights of any person or entity, by you (or anyone using any of your accounts) or by your User Submissions. If you are a Professional, you also agree to indemnify, defend, and hold harmless the Indemnified Parties from and against any and all claims relating to or that may be asserted by your clients. LetsDivorce reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with LetsDivorce in asserting any available defenses.</p> 

                <h4>12. Minors; Ability to Accept Terms of Service.</h4> 
                <p>The Service is not intended for children uner 18 years of age. If you are under 18 years of age, please do not use the Service. <strong>You affirm that you are the applicable age of majority in your jurisdiction of residence or older.</strong></p>

                <h4>13. Choice of Law; Arbitration.</h4> 
                <p>These Terms, any AdditionalTerms, and any dispute arising from or relating to these Terms, the Additional Terms or the provision or use of the Service, shall be governed exclusively by, and construed in accordance with the laws of the United States and the State of Montana, without reference to any conflict of laws principles. Any controversy, claim, or dispute arising out of or related to these Terms (or the interpretation, performance, or breach of them), the Site or the Services, including but not limited to alleged violations of state or federal statutory or common law rights or duties (a “<strong>Dispute</strong>”) shall be solely and exclusively resolved according to the procedures set forth in this paragraph. If we are unable to resolve any Dispute through informal means, either party may initiate binding arbitration of such Dispute. The arbitration shall be initiated and conducted according to the JAMS/Endispute Comprehensive Arbitration Rules and Procedures in effect as of the date hereof, including the Optional Appeal Procedure provided for in such rules (the “Arbitration Rules”). The arbitration shall be conducted in Louisville, Kentucky before a single neutral arbitrator appointed in accordance with the Arbitration Rules. The arbitrator’s decision shall be controlled by these Terms, including any applicable Additional Terms. No Disputes may be arbitrated on a class or representative basis. Arbitration can decide only the individual Dispute and the arbitrator may not consolidate or join the claims of other persons or parties who may be similarly situated. BY ENTERING INTO THESE TERMS, YOU HEREBY IRREVOCABLY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH THOSE OF OTHERS IN THE FORM OF A CLASS ACTION OR SIMILAR PROCEDURAL DEVICE. ANY CLAIMS ARISING OUT OF, RELATING TO, OR CONNECTED WITH THESE TERMS MUST BE ASSERTED INDIVIDUALLY. The arbitrator shall not have the power to award punitive damages against any party.</p> 

                <h4>14. International Use.</h4>   
                <p>We do not represen or warrant that the Service, or any part of it, is appropriate or available for use in any particular jurisdiction. You access the Service on your own initiative and at your own risk, and are responsible for complying with all local laws, rules and regulations. We may limit the availability of Service, in whole or in part, to any person, geographic area or jurisdiction we choose, at any time and in our sole discretion.</p> 

                <h4>15. Miscellaneous.</h4>
                <p>These Terms and any Additional Terms constitute the entire and exclusive and final statement of the agreement between you and LetsDivorce, and govern your use of the Service. The failure of LetsDivorce to exercise or enforce any right or provision of these Terms or any Additional Terms shall not constitute a waiver of such right or provision. If for any reason any provision of these Terms or any Additional Terms is found to be unenforceable, that provision shall be enforced to the maximum extent permissible to give effect to the intent of the parties, and the remainder of these Terms and any Additional Terms shall continue in full force and effect. The section titles in these Terms and any Additional Terms are for convenience only and have no legal or contractual effect.</p> 

                <h4>Modifications to Terms.</h4> 
                <p>LetsDivorce may, in itssole and absolute discretion, change these Terms from time to time. All changes to the Terms or the Privacy Policy will be effective when posted, and we will provide notification of such changes to you via the Service or contact information you may have provided to LetsDivorce upon registration. Your continued use of the Service following any changes to the Terms or the Privacy Policy will constitute your agreement to be bound by such changes. If you object to any such changes, your sole recourse shall be to cease using the Service.</p> 
                <p>The effective date of these Terms is June 1, 2018.</p> 
                
                </div>
            </div>
        </div>
    </div>
)

export default TosPage
